import Head from 'next/head'
import Header from './components/Header';
import Footer from './components/Footer';
import forums from '../db/forums.json';
import Login from './components/Login';
import Signup from './components/Signup';

export default function LoginPage() {
  return (
    <div className='h-screen'>
      <Head>
        <title>Distance Skateboarding</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main className='flex flex-col sm:flex-row sm:justify-center sm:items-center'>
        <Login />
        <Signup />
      </main>
      <Footer />
    </div>
  )
}
