import Head from 'next/head'
import Header from './components/Header';
import Footer from './components/Footer';
import Login from './components/Login';

export default function Home() {
  return (
    <div className='h-screen'>
      <Head>
        <title>Distance Skateboarding</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Login />
      <Footer />
    </div>
  )
}
